[2024-02-18T00:11:44.361+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Read_and_load_of_API_to_MySQLDB.companies_table scheduled__2024-02-11T00:00:00+00:00 [queued]>
[2024-02-18T00:11:44.386+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Read_and_load_of_API_to_MySQLDB.companies_table scheduled__2024-02-11T00:00:00+00:00 [queued]>
[2024-02-18T00:11:44.388+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 6
[2024-02-18T00:11:44.419+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): companies_table> on 2024-02-11 00:00:00+00:00
[2024-02-18T00:11:44.428+0000] {standard_task_runner.py:60} INFO - Started process 274 to run task
[2024-02-18T00:11:44.433+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Read_and_load_of_API_to_MySQLDB', 'companies_table', 'scheduled__2024-02-11T00:00:00+00:00', '--job-id', '478', '--raw', '--subdir', 'DAGS_FOLDER/CRM.py', '--cfg-path', '/tmp/tmpk38c5jt4']
[2024-02-18T00:11:44.437+0000] {standard_task_runner.py:88} INFO - Job 478: Subtask companies_table
[2024-02-18T00:11:44.550+0000] {task_command.py:423} INFO - Running <TaskInstance: Read_and_load_of_API_to_MySQLDB.companies_table scheduled__2024-02-11T00:00:00+00:00 [running]> on host 3cac75bda9a8
[2024-02-18T00:11:44.732+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jmoc' AIRFLOW_CTX_DAG_ID='Read_and_load_of_API_to_MySQLDB' AIRFLOW_CTX_TASK_ID='companies_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-11T00:00:00+00:00'
[2024-02-18T00:11:44.750+0000] {base.py:83} INFO - Using connection ID 'mysql_connection' for task execution.
[2024-02-18T00:11:44.772+0000] {sql.py:450} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS ***.companies(
              id INT AUTO_INCREMENT  PRIMARY KEY NOT NULL,
              name VARCHAR(25) NOT NULL UNIQUE  ,
              catchPhrase VARCHAR(225) NOT NULL,
              bs VARCHAR(50) NOT NULL 
            );
            , parameters: None
[2024-02-18T00:11:44.776+0000] {sql.py:459} INFO - Rows affected: 0
[2024-02-18T00:11:44.792+0000] {base.py:83} INFO - Using connection ID 'postgres_connection' for task execution.
[2024-02-18T00:11:44.800+0000] {sql.py:450} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS ***.companies(
              id BIGSERIAL PRIMARY KEY NOT NULL,
              name VARCHAR(25) NOT NULL UNIQUE  ,
              catchPhrase VARCHAR(225) NOT NULL,
              bs VARCHAR(50) NOT NULL 
            );
            , parameters: None
[2024-02-18T00:11:44.808+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/CRM.py", line 47, in companies_table
    postgres_hook.run(db.companies_c('postgres'))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidSchemaName: schema "***" does not exist
LINE 2:             CREATE TABLE IF NOT EXISTS ***.companies(
                                               ^

[2024-02-18T00:11:44.843+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Read_and_load_of_API_to_MySQLDB, task_id=companies_table, execution_date=20240211T000000, start_date=20240218T001144, end_date=20240218T001144
[2024-02-18T00:11:44.870+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 478 for task companies_table (schema "***" does not exist
LINE 2:             CREATE TABLE IF NOT EXISTS ***.companies(
                                               ^
; 274)
[2024-02-18T00:11:44.896+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-18T00:11:44.962+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
