[2024-02-18T04:46:40.715+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_From_an_API_to_MySQL_Postgres_and_Redis.load_companies_to_MySQL_and_Postgres scheduled__2024-01-14T00:00:00+00:00 [queued]>
[2024-02-18T04:46:40.884+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_From_an_API_to_MySQL_Postgres_and_Redis.load_companies_to_MySQL_and_Postgres scheduled__2024-01-14T00:00:00+00:00 [queued]>
[2024-02-18T04:46:40.888+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-18T04:46:41.070+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): load_companies_to_MySQL_and_Postgres> on 2024-01-14 00:00:00+00:00
[2024-02-18T04:46:41.081+0000] {standard_task_runner.py:60} INFO - Started process 5962 to run task
[2024-02-18T04:46:41.135+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ETL_From_an_API_to_MySQL_Postgres_and_Redis', 'load_companies_to_MySQL_and_Postgres', 'scheduled__2024-01-14T00:00:00+00:00', '--job-id', '604', '--raw', '--subdir', 'DAGS_FOLDER/CRM.py', '--cfg-path', '/tmp/tmpj39kihx3']
[2024-02-18T04:46:41.148+0000] {standard_task_runner.py:88} INFO - Job 604: Subtask load_companies_to_MySQL_and_Postgres
[2024-02-18T04:46:41.582+0000] {task_command.py:423} INFO - Running <TaskInstance: ETL_From_an_API_to_MySQL_Postgres_and_Redis.load_companies_to_MySQL_and_Postgres scheduled__2024-01-14T00:00:00+00:00 [running]> on host 091c4b0f3ebe
[2024-02-18T04:46:42.397+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jmoc' AIRFLOW_CTX_DAG_ID='ETL_From_an_API_to_MySQL_Postgres_and_Redis' AIRFLOW_CTX_TASK_ID='load_companies_to_MySQL_and_Postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-01-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-14T00:00:00+00:00'
[2024-02-18T04:46:42.562+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/CRM.py", line 80, in load_companies_to_MySQL_and_Postgres
    for x in companies:
TypeError: 'NoneType' object is not iterable
[2024-02-18T04:46:42.629+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_From_an_API_to_MySQL_Postgres_and_Redis, task_id=load_companies_to_MySQL_and_Postgres, execution_date=20240114T000000, start_date=20240218T044640, end_date=20240218T044642
[2024-02-18T04:46:42.844+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 604 for task load_companies_to_MySQL_and_Postgres ('NoneType' object is not iterable; 5962)
[2024-02-18T04:46:42.957+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-18T04:46:43.200+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
